### ISSUE TITLE
crash when right clicking a lit bonfire

### ISSUE THREAD

**Issue by lag42** [Wehavecookies56/Bonfires#19]
i am on 1.12.2, mystcraft updated to 1.12 about an hour ago as of making this issue

crash log here:
https://paste.dimdev.org/tibacaxaxa.txt

**Comment by Wehavecookies56** [comment]
Does this definitely only happen when Mystcraft is installed?
Also if you don't mind would you be able to send me your world?

**Comment by lag42** [comment]
it didn't happen even though i have mystcraft installed in another world, i really should have tried to reproduce it first before reporting it i also unfortunately deleted the world already but i'll try to make it happen again

**Comment by lag42** [comment]
i can't reproduce it, sorry for your time

**Comment by Wehavecookies56** [comment]
Actually I've managed to reproduce it and it turns out it was due to an error in my dimension page indexing code. I've now fixed it and will likely release a new version with the fix soon.
In the meantime if you run into the error try creating new dimensions as it should only happen when there are enough to fill a page -1 so 5, 11, 17, etc. should cause the crash currently.
